/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrimiteRouteImport } from './routes/trimite'
import { Route as CategoriiRouteImport } from './routes/categorii'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemaIdRouteImport } from './routes/problema.$id'

const TrimiteRoute = TrimiteRouteImport.update({
  id: '/trimite',
  path: '/trimite',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriiRoute = CategoriiRouteImport.update({
  id: '/categorii',
  path: '/categorii',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemaIdRoute = ProblemaIdRouteImport.update({
  id: '/problema/$id',
  path: '/problema/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categorii': typeof CategoriiRoute
  '/trimite': typeof TrimiteRoute
  '/problema/$id': typeof ProblemaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categorii': typeof CategoriiRoute
  '/trimite': typeof TrimiteRoute
  '/problema/$id': typeof ProblemaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categorii': typeof CategoriiRoute
  '/trimite': typeof TrimiteRoute
  '/problema/$id': typeof ProblemaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categorii' | '/trimite' | '/problema/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categorii' | '/trimite' | '/problema/$id'
  id: '__root__' | '/' | '/categorii' | '/trimite' | '/problema/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriiRoute: typeof CategoriiRoute
  TrimiteRoute: typeof TrimiteRoute
  ProblemaIdRoute: typeof ProblemaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trimite': {
      id: '/trimite'
      path: '/trimite'
      fullPath: '/trimite'
      preLoaderRoute: typeof TrimiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorii': {
      id: '/categorii'
      path: '/categorii'
      fullPath: '/categorii'
      preLoaderRoute: typeof CategoriiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problema/$id': {
      id: '/problema/$id'
      path: '/problema/$id'
      fullPath: '/problema/$id'
      preLoaderRoute: typeof ProblemaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriiRoute: CategoriiRoute,
  TrimiteRoute: TrimiteRoute,
  ProblemaIdRoute: ProblemaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
